### PR TITLE
adds module import snippets

### LINKED ISSUE #24: No destructuring?
I did the destructuring thing for a while (`const { Component } = Ember;`) but it seems to have fallen out of favor. Wondering if we could/should switch back to Ember.Component, like in the guides?

Also I just saw this tweet: https://twitter.com/MiguelCamba/status/884724694871666688. It would be nice to add these soon, but I'm not sure about what they depend on.

### PR DESCRIPTION
**Pull request by jbailey4**
Merges [atom-ember-module-snippets](https://github.com/jbailey4/atom-ember-module-snippets) as discussed in https://github.com/jbailey4/atom-ember-module-snippets/issues/3

@mattmcmanus I added all the snippets as I had them originally, let me know if we want to add/remove some code. The only real differences I see are:
  - use of `leftLabelHTML` to add some Ember branding (i.e. `#E46651`)
  - the top-level Ember classes are separated into individual snippet files, to allow easier additions/deletions

Closes #24

### CODE REVIEW

**Comment by jbailey4** [comment]
@mattmcmanus I did try nested folders, but it seems atom doesn't currently support nested snippets, see this issue -> https://github.com/atom/snippets/issues/28

I'm okay with the `import-` prefix. I'll go ahead and add that.

**Comment by jbailey4** [comment]
@mattmcmanus Okay good to go, added the `import-` prefix (https://github.com/mattmcmanus/atom-ember-snippets/pull/26/commits/b8e128c1f6b3c4fe3f4ccac32abdedca773acbd0)

**Comment by jbailey4** [comment]
@mattmcmanus ping. 

once this is merged, I'll deprecate atom-ember-module-snippets and instruct users to use this package instead

**Comment by mattmcmanus** [comment]
Sorry @jbailey4! Time got away from me. I'll cut a release tonight.

**Comment by mattmcmanus** [comment]
I just shipped `2.1.0` Let me know what you think

**Comment by jbailey4** [comment]
@mattmcmanus No problem. Updated and looks good 👍 Thanks for getting this in

**Pull request merged**
