### PR TITLE
Ember Data Factory Guy Snippets

### PR DESCRIPTION
**Pull request by Oreoz**
Seeing that you have some snippets for Mirage, I added a couple for the Factory Guy users out there (like me).

Cheers!

### CODE REVIEW

**Comment by Oreoz** [comment]
@mattmcmanus Could you take a look when you have a chance? Thanks!

**Comment by mattmcmanus** [comment]
I'm still pondering this one. Opening the plugin up to addons seems to be a can or worms. When I took over maintenance of this repo, I added mirage simply because it was in my collection of ember related snippets. Also, I've noticed that the huge addition of all the new imports has had a performance impact on the package, which causes me further pause. 

I think the cleanest solution would be for me to remove mirage snippets. Maybe we can use the readme to link to gists with the snippets for various ember addons? That way people could add them to their personal snippets files if they want.

What do you think?

**Comment by Oreoz** [comment]
I actually quite like the idea of removing addon-related snippets come to think of it and keep this project solely for Ember snippets.

I could maintain the ember-data-factory-guy related snippets using a README file in another repo and people would be able to select whatever they need and add those to their local Atom snippets.

I think you can close this PR for now and I'll setup a simple repo to keep track of useful factory-guy snippets. 

Once I'm done with that, I'll submit another PR to this project in order to link to it in the README and explain why you're steering away from addon-related snippets (if that makes any sense for you). The list of addon-related snippets could then live in the README of this repo instead of loading all unessential snippets for every user.

**Comment by mattmcmanus** [comment]
Ok great. Sounds like a good plan to me. I'll pull out the mirage soon as well.

**Pull request closed without merging**
